<?xml version="1.0" encoding="utf-8"?><Database Name="LibraryDatabase" Class="LibraryDataLinqClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
	<Table Name="dbo.Events" Member="Events">
		<Type Name="Event">
			<Column Name="eventId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
			<Column Name="StateId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
			<Column Name="userId" Type="System.Int32" DbType="Int" CanBeNull="true" />
			<Association Name="State_Event" Member="State" ThisKey="StateId" OtherKey="StateId" Type="State" IsForeignKey="true" />
			<Association Name="User_Event" Member="User" ThisKey="userId" OtherKey="userId" Type="User" IsForeignKey="true" />
		</Type>
	</Table>
	<Table Name="dbo.Catalogs" Member="Catalogs">
		<Type Name="Catalog">
			<Column Name="catalogId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
			<Column Name="title" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
			<Column Name="author" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
			<Column Name="nrOfPages" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
			<Association Name="Catalog_State" Member="States" ThisKey="catalogId" OtherKey="catalogId" Type="State" />
		</Type>
	</Table>
	<Table Name="dbo.States" Member="States">
		<Type Name="State">
			<Column Name="StateId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
			<Column Name="NrOfBooks" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
			<Column Name="catalogId" Type="System.Int32" DbType="Int" CanBeNull="true" />
			<Association Name="State_Event" Member="Events" ThisKey="StateId" OtherKey="StateId" Type="Event" />
			<Association Name="Catalog_State" Member="Catalog" ThisKey="catalogId" OtherKey="catalogId" Type="Catalog" IsForeignKey="true" />
		</Type>
	</Table>
	<Table Name="dbo.Users" Member="Users">
		<Type Name="User">
			<Column Name="userId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
			<Column Name="firstName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
			<Column Name="lastName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
			<Association Name="User_Event" Member="Events" ThisKey="userId" OtherKey="userId" Type="Event" />
		</Type>
	</Table>
</Database>